import type { NextPage } from 'next'
import Head from "next/head";
import {useEffect, useState} from "react";
import Image from "next/image";
import {Box, Button, Divider, Grid, IconButton, MenuItem, TextField, Typography} from "@mui/material";
import ShareIcon from '@mui/icons-material/Share';
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder';

const Company: NextPage = () => {

  const [fixHeader, setFixHeader] = useState(false);

  const onScroll = () => {
    const scrollTop = window.pageYOffset;
    scrollTop > 150 ? setFixHeader(true) : setFixHeader(false);
  };

  const [startDate, setStartDate] = useState<any>();

  useEffect(() => {
    const now = new Date();

    const year = now.getFullYear();
    const month = now.getMonth() + 1;

    setStartDate(new Date(year, month, 1))
    setFeature("/imalsan/main.png");

    window.addEventListener("scroll", onScroll);
    return () => {
      window.removeEventListener("scroll", onScroll);
    };
  }, []);

  // const selectDateOption = () => {
  //   const now = new Date();
  //
  //   const year = now.getFullYear();
  //   const month = now.getMonth() + 1;
  //
  //   const result = [];
  //
  //   let i = 1;
  //   while (startDate <= new Date(year, month + 1, 0)) {
  //     result.push(
  //       <option key={i}>
  //         startDate.toISOString().split('T')[0]
  //       </option>
  //     );
  //     i++;
  //     startDate.setDate(startDate.getDate() + 1);
  //   }
  //
  //   console.log(result);
  //
  //   return result;
  // }

  const [feature, setFeature] = useState<string>();

  const onChangeFeature = (e: any) => {
    console.log(e.target);
  }

  return (
    <div style={{ minWidth: "1200px" }}>
      <Head>
        <title>ストーリーツアー - 会員加入</title>

        <meta property="og:url" content="https://www.sanppo.co.kr/" />
        <meta property="og:title" content="ストーリーツアー" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="/main.jpeg" />
        {/*<meta property="og:description" content="공유기능 | 열심히 코드를 공부합시다." />*/}
        {/*<meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" href="/icon.svg" />
      </Head>

      <div style={{ position: "relative" }}>
        <header style={
          fixHeader ?
            { backgroundColor: "#383838", height: "150px", lineHeight: "150px", zIndex: "9999", position: "fixed", left: 0, right: 0, display: "flex", justifyContent: "space-around" } :
            { backgroundColor: "#383838", height: "150px", lineHeight: "150px", zIndex: "9999", position: "absolute", left: 0, right: 0, display: "flex", justifyContent: "space-around" }
        }>
          <div>
            <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "35px" }}>
              ストーリーツアー
            </a>
          </div>

          <div>
            <ul style={{ margin: 0, padding: 0 }}>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/Company"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  会社紹介
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/Products/Imalsan"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  プログラム
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  ギャラリー
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  CONTACT US
                </a>
              </li>
            </ul>
          </div>
          <div>
            <a href={"/Membership"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: 700, background: "#f5343d", padding: "8px 15px", borderRadius: "10px" }}>
              予約確認
            </a>
          </div>
        </header>

        <div style={{ maxWidth: 1200, margin: "0 auto", paddingTop: 200, paddingBottom: 50 }}>

          <Divider>
            <Typography variant={"h4"}>
              会社紹介
            </Typography>
          </Divider>

          <Box sx={{ position: "relative", width: 950, height: 650, m: "50px auto" }}>
            <Image src={"/info.jpeg"} alt={"会社紹介"} fill />
          </Box>

          <Divider />

          <Box sx={{ position: "relative", width: 950, height: 650, m: "50px auto" }}>
            <Grid container>
              <Grid item xs={4}>
                <div style={{ position: "relative", width: 250, height: 150, margin: "0 auto" }}>
                  <Image src={"/info1.jpeg"} alt={""} fill />
                </div>
                <div style={{ position: "relative", width: 250, height: 400, margin: "50px auto 0" }}>
                  <Image src={"/info2.jpeg"} alt={""} fill />
                </div>
              </Grid>
              <Grid
                item
                xs={8}
                sx={{
                  "& li": { mb: 2.5 },
                  "& ul > li > ul > li": { my: 1.8 },
                }}
              >
                <ul style={{ listStyle: "hiragana", marginTop: 0, }}>
                  <li>
                    沿革
                    <ul style={{ listStyle: "katakana" }}>
                      <li>岩崎グループソウル事務所（2004年～現在）</li>
                      <li>ストーリーツアー（株）法人設立（2012年4月24日～現在）</li>
                    </ul>
                  </li>
                  <li>
                    主要業務
                    <ul style={{ listStyle: "katakana" }}>
                      <li>岩崎ホテル含む南九州ホテル手配</li>
                      <li>指宿ゴルフクラブ、種子島ゴルフクラブ手配</li>
                      <li>指宿ゴルフパック、霧島ゴルフパック手配及び運営</li>
                      <li>鹿児島交通含む南九州全地域バス手配</li>
                      <li>鹿児島ー屋久島間高速船トッピー予約事務所</li>
                      <li>屋久島内ホテル及び民宿手配</li>
                    </ul>
                  </li>
                  <li>
                    イベント進行内訳
                    <ul style={{ listStyle: "katakana" }}>
                      <li>鹿児島県主催ランド会社招待ツアー現地案内（2005年～2013年）</li>
                      <li>屋久島トラッキングツアー</li>
                      <li>霧島の韓国岳トラッキングツアー</li>
                      <li>大韓空港優秀代理店ツアー（指宿ゴルフクラブ、指宿岩崎ホテル）</li>
                      <li>明治維新歴史紀行</li>
                      <li>鹿児島通販進行</li>
                    </ul>
                  </li>
                </ul>
              </Grid>
            </Grid>
          </Box>
        </div>

        <footer style={{ background: "#f5343d", color: "white", padding: 50, lineHeight: .5, textAlign: "center" }}>
          <p>
            Copyright ⓒ 2022 STORY TOUR All Rights Reserved
          </p>
          <p>
            NATOUR
          </p>
        </footer>

      </div>
    </div>
  )
}

export default Company;
