import type { NextPage } from 'next'
import Head from "next/head";
import {useEffect, useState} from "react";
import Image from "next/image";
import {Box, Button, Divider, Grid, IconButton, MenuItem, TextField, Typography} from "@mui/material";
import ShareIcon from '@mui/icons-material/Share';
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder';
import {Masonry} from "@mui/lab";

const Gallery: NextPage = () => {

  const [fixHeader, setFixHeader] = useState(false);

  const onScroll = () => {
    const scrollTop = window.pageYOffset;
    scrollTop > 150 ? setFixHeader(true) : setFixHeader(false);
  };

  const [startDate, setStartDate] = useState<any>();

  useEffect(() => {
    const now = new Date();

    const year = now.getFullYear();
    const month = now.getMonth() + 1;

    setStartDate(new Date(year, month, 1))
    setFeature("/imalsan/main.png");

    window.addEventListener("scroll", onScroll);
    return () => {
      window.removeEventListener("scroll", onScroll);
    };
  }, []);

  const [feature, setFeature] = useState<string>();

  const onChangeFeature = (e: any) => {
    console.log(e.target);
  }

  return (
    <div style={{ minWidth: "1200px" }}>
      <Head>
        <title>ストーリーツアー - ギャラリー</title>

        <meta property="og:url" content="https://www.sanppo.co.kr/" />
        <meta property="og:title" content="ストーリーツアー" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="/main.jpeg" />
        {/*<meta property="og:description" content="공유기능 | 열심히 코드를 공부합시다." />*/}
        {/*<meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" href="/icon.svg" />
      </Head>

      <div style={{ position: "relative" }}>
        <header style={
          fixHeader ?
            { backgroundColor: "#383838", height: "150px", lineHeight: "150px", zIndex: "9999", position: "fixed", left: 0, right: 0, display: "flex", justifyContent: "space-around" } :
            { backgroundColor: "#383838", height: "150px", lineHeight: "150px", zIndex: "9999", position: "absolute", left: 0, right: 0, display: "flex", justifyContent: "space-around" }
        }>
          <div>
            <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "35px" }}>
              ストーリーツアー
            </a>
          </div>

          <div>
            <ul style={{ margin: 0, padding: 0 }}>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/Company"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  会社紹介
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/Products/Imalsan"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  プログラム
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/Gallery"} target={"_parent"} style={{ color: "#f5343d", fontSize: "15px", fontWeight: "700" }}>
                  ギャラリー
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  CONTACT US
                </a>
              </li>
            </ul>
          </div>
          <div>
            <a href={"/Membership"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: 700, background: "#f5343d", padding: "8px 15px", borderRadius: "10px" }}>
              予約確認
            </a>
          </div>
        </header>

        <div style={{ maxWidth: 1200, margin: "0 auto", paddingTop: 200, paddingBottom: 50 }}>
          <Box>
            <Masonry>
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub1.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub2.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub3.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub4.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub5.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub6.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub7.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub8.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub9.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub10.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub11.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub12.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub13.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub14.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub15.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub16.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub17.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub18.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub19.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub20.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub21.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub22.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub23.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub24.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub25.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub26.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub27.jpg"} alt={""} />
              <img src={"https://s3storytour.s3.ap-northeast-2.amazonaws.com/gallery/sub28.jpg"} alt={""} />
            </Masonry>
          </Box>
        </div>

        <footer style={{ background: "#f5343d", color: "white", padding: 50, lineHeight: .5, textAlign: "center" }}>
          <p>
            Copyright ⓒ 2022 STORY TOUR All Rights Reserved
          </p>
          <p>
            NATOUR
          </p>
        </footer>

      </div>
    </div>
  )
}

export default Gallery;
