import type { NextPage } from 'next'
import Head from "next/head";
import {useEffect, useState} from "react";
import Image from "next/image";
import {Button, IconButton, MenuItem, TextField, Typography} from "@mui/material";
import ShareIcon from '@mui/icons-material/Share';

const Membership: NextPage = () => {

  const [fixHeader, setFixHeader] = useState(false);

  const onScroll = () => {
    const scrollTop = window.pageYOffset;
    scrollTop > 150 ? setFixHeader(true) : setFixHeader(false);
  };

  const [startDate, setStartDate] = useState<any>();

  useEffect(() => {
    const now = new Date();

    const year = now.getFullYear();
    const month = now.getMonth() + 1;

    setStartDate(new Date(year, month, 1))

    window.addEventListener("scroll", onScroll);
    return () => {
      window.removeEventListener("scroll", onScroll);
    };
  }, []);

  // const selectDateOption = () => {
  //   const now = new Date();
  //
  //   const year = now.getFullYear();
  //   const month = now.getMonth() + 1;
  //
  //   const result = [];
  //
  //   let i = 1;
  //   while (startDate <= new Date(year, month + 1, 0)) {
  //     result.push(
  //       <option key={i}>
  //         startDate.toISOString().split('T')[0]
  //       </option>
  //     );
  //     i++;
  //     startDate.setDate(startDate.getDate() + 1);
  //   }
  //
  //   console.log(result);
  //
  //   return result;
  // }

  return (
    <div style={{ minWidth: "1200px" }}>
      <Head>
        <title>ストーリーツアー - 会員加入</title>

        <meta property="og:url" content="https://www.sanppo.co.kr/" />
        <meta property="og:title" content="ストーリーツアー" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="/main.jpeg" />
        {/*<meta property="og:description" content="공유기능 | 열심히 코드를 공부합시다." />*/}
        {/*<meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" href="/icon.svg" />
      </Head>

      <div style={{ position: "relative" }}>
        <header style={
          fixHeader ?
            { backgroundColor: "#383838", height: "150px", lineHeight: "150px", zIndex: "9999", position: "fixed", left: 0, right: 0, display: "flex", justifyContent: "space-around" } :
            { backgroundColor: "#383838", height: "150px", lineHeight: "150px", zIndex: "9999", position: "absolute", left: 0, right: 0, display: "flex", justifyContent: "space-around" }
        }>
          <div>
            <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "35px" }}>
              ストーリーツアー
            </a>
          </div>

          <div>
            <ul style={{ margin: 0, padding: 0 }}>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  会社紹介
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/Products/Imalsan"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  プログラム
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  ギャラリー
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  CONTACT US
                </a>
              </li>
            </ul>
          </div>
          <div>
            <a href={"/Membership"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: 700, background: "#f5343d", padding: "8px 15px", borderRadius: "10px" }}>
              予約確認
            </a>
          </div>
        </header>

        <div style={{ display: "flex", maxWidth: 1200, margin: "0 auto", paddingTop: 200 }}>
          <div style={{ width: "50%" }}>
            {/* 사진 */}
            <div style={{ position: "relative", border: "1px solid gray", width: 500, height: 500, margin: "0 auto" }}>
              <Image src={"/imalsan/main.png"} alt={"상품 메인"} fill />
            </div>

            {/* 상품 리스트 */}
            <div>
              <ul style={{ display: "flex", justifyContent: "space-between", flexWrap: "wrap", maxWidth: 500, margin: "30px auto", padding: 0, fontSize: 0, listStyle: "none" }}>
                <li style={{ position: "relative", border: "1px solid gray", width: 60, height: 60, marginBottom: 10 }}>
                  <Image src={"/imalsan/sub1.jpg"} alt={"상품 이미지1"} fill />
                </li>
                <li style={{ position: "relative", border: "1px solid gray", width: 60, height: 60, marginBottom: 10 }}>
                  <Image src={"/imalsan/sub2.jpg"} alt={"상품 이미지1"} fill />
                </li>
                <li style={{ position: "relative", border: "1px solid gray", width: 60, height: 60, marginBottom: 10 }}>
                  <Image src={"/imalsan/sub3.jpg"} alt={"상품 이미지1"} fill />
                </li>
                <li style={{ position: "relative", border: "1px solid gray", width: 60, height: 60, marginBottom: 10 }}>
                  <Image src={"/imalsan/sub4.jpg"} alt={"상품 이미지1"} fill />
                </li>
                <li style={{ position: "relative", border: "1px solid gray", width: 60, height: 60, marginBottom: 10 }}>
                  <Image src={"/imalsan/sub5.jpg"} alt={"상품 이미지1"} fill />
                </li>
                <li style={{ position: "relative", border: "1px solid gray", width: 60, height: 60, marginBottom: 10 }}>
                  <Image src={"/imalsan/sub6.jpg"} alt={"상품 이미지1"} fill />
                </li>
                <li style={{ position: "relative", border: "1px solid gray", width: 60, height: 60, marginBottom: 10 }}>
                  <Image src={"/imalsan/sub7.jpg"} alt={"상품 이미지1"} fill />
                </li>
                <li style={{ position: "relative", border: "1px solid gray", width: 60, height: 60, marginBottom: 10 }}>
                  <Image src={"/imalsan/sub8.jpg"} alt={"상품 이미지1"} fill />
                </li>
                <li style={{ position: "relative", border: "1px solid gray", width: 60, height: 60, marginBottom: 10 }}>
                  <Image src={"/imalsan/sub9.jpg"} alt={"상품 이미지1"} fill />
                </li>
                {/*<li style={{ position: "relative", border: "1px solid gray", width: 60, height: 60, marginBottom: 10 }}>*/}
                {/*  <Image src={"/imalsan/sub10.jpg"} alt={"상품 이미지1"} fill />*/}
                {/*</li>*/}
              </ul>
            </div>
          </div>

          {/* 상품 정보 */}
          <div style={{ width: "50%" }}>
            <div style={{ width: 500, margin: "0 auto" }}>
              <div>
                <h4 style={{ fontSize: 30, fontWeight: "normal", margin: 0 }}>莉茉山と韓屋村</h4>

                <div style={{ display: "flex", justifyContent: "space-between", margin: "30px 0" }}>
                  {/*<div style={{ border: "1px solid gray", width: 45, height: 45, color: "gray" }}>*/}
                  {/*  <ShareIcon />*/}
                  {/*</div>*/}
                  <Button variant={"outlined"} sx={{ minWidth: 45, borderColor: "gray", color: "gray" }}>
                    <ShareIcon />
                  </Button>

                  <p style={{ fontSize: 24, margin: 0, marginTop: 15, fontWeight: "normal", color: "gray", textAlign: "right" }}>
                    90,000 원
                  </p>
                </div>
              </div>
              <hr />
              <div>
                <p>삼각산 비봉능선의 향로봉에서 서북쪽으로 뻗은 산줄기가 기자촌을 지나 구파발역 북쪽에서 솟아오른 산봉우리</p>

                <p>#매일출발 #이말산 #트레킹</p>
              </div>
              <div
                style={{
                  border: "1px solid gray",
                  padding: "30px 50px",
                  // marginTop: 50,
                  margin: "50px auto",
                  // textAlign: "center",
                  width: 500
                }}
              >
                <Typography sx={{ mb: 2 }}>
                  출발일
                </Typography>

                <TextField
                  label={"출발일 (필수)"}
                  select
                  size={"small"}
                  fullWidth
                >
                  <MenuItem>12월 20일</MenuItem>
                  <MenuItem>12월 21일</MenuItem>
                  <MenuItem>12월 22일</MenuItem>
                  <MenuItem>12월 23일</MenuItem>
                  <MenuItem>12월 24일</MenuItem>
                  <MenuItem>12월 25일</MenuItem>
                  <MenuItem>12월 26일</MenuItem>
                  <MenuItem>12월 27일</MenuItem>
                  <MenuItem>12월 28일</MenuItem>
                  <MenuItem>12월 29일</MenuItem>
                  <MenuItem>12월 30일</MenuItem>
                  <MenuItem>12월 31일</MenuItem>
                </TextField>

                <div style={{ display: "flex", justifyContent: "space-between", marginTop: 30 }}>
                  <Button variant={"outlined"} size={"large"} sx={{ width: "30%" }}>구매하기</Button>
                  <Button variant={"outlined"} size={"large"} sx={{ width: "30%" }}>장바구니</Button>
                  <Button variant={"outlined"} size={"large"} sx={{ width: "30%" }}>좋아요</Button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <hr />

        <div style={{ display: "flex", maxWidth: 800, minHeight: 500, margin: "0 auto", padding: 50 }}>
          <div style={{ position: "relative", width: "100%", height: "100%", minHeight: 850 }}>
            <Image src={"/imalsan/test.jpeg"} alt={"상세 페이지"} fill />
          </div>
        </div>



        <footer style={{ background: "#f5343d", color: "white", padding: 50, lineHeight: .5, textAlign: "center" }}>
          <p>
            Copyright ⓒ 2022 STORY TOUR All Rights Reserved
          </p>
          <p>
            NATOUR
          </p>
        </footer>

      </div>
    </div>
  )
}

export default Membership
