import type { NextPage } from 'next'
import Head from 'next/head'
import Image from "next/image";
import {useEffect, useState} from "react";

const Home: NextPage = () => {

  const [fixHeader, setFixHeader] = useState(false);

  const onScroll = () => {
    const scrollTop = window.pageYOffset;
    scrollTop > 150 ? setFixHeader(true) : setFixHeader(false);
  };

  useEffect(() => {
    window.addEventListener("scroll", onScroll);
    return () => {
      window.removeEventListener("scroll", onScroll);
    };
  }, []);

  return (
    <div style={{ minWidth: "1200px" }}>
      <Head>
        <title>ストーリーツアー</title>

        <meta property="og:url" content="https://www.sanppo.co.kr/" />
        <meta property="og:title" content="ストーリーツアー" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="/main.jpeg" />
        {/*<meta property="og:description" content="공유기능 | 열심히 코드를 공부합시다." />*/}
        {/*<meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" href="/icon.svg" />
      </Head>

      <div style={{ position: "relative" }}>
        <header style={
          fixHeader ?
          { backgroundColor: "#383838", height: "150px", lineHeight: "150px", zIndex: "9999", position: "fixed", left: 0, right: 0, display: "flex", justifyContent: "space-around" } :
          { height: "150px", lineHeight: "150px", zIndex: "9999", position: "absolute", left: 0, right: 0, display: "flex", justifyContent: "space-around" }
        }>
          <div>
            <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "35px" }}>
              ストーリーツアー
            </a>
          </div>

          <div>
            <ul style={{ margin: 0, padding: 0 }}>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/Company"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  会社紹介
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/Products/Imalsan"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  プログラム
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/Gallery"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  ギャラリー
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  CONTACT US
                </a>
              </li>
            </ul>
          </div>
          <div>
            <a href={"/Membership"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: 700, background: "#f5343d", padding: "8px 15px", borderRadius: "10px" }}>
              会員加入
            </a>
          </div>
        </header>
      </div>

      <div style={{ position: "relative", height: "900px" }}>
        <div style={{ height: "100%", backgroundImage: "url('/main.jpeg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "50% 50%" }}>

        </div>
        {/*<Image src={"/main.jpeg"} alt={"배경이미지"} fill />*/}
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#383838", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ float: "left", width: "50%", fontSize: "48px", textAlign: "center" }}>
          プログラム
        </div>
        <div style={{ float: "right", width: "50%" }}>
          山と都心を一緒に楽しめるソウルの特徴を生かし、<br />北漢山ドゥルレ道、恩平ドゥルレ道、恩平韓屋村、<br />そして津寛寺テンプルステイを連携します。<br /><br />

          現地の登山ガイドの案内を受けて山の話、木の話、<br />山と地域住民との関係の話を聞きながら山の旅を楽しむのが<br />一般的な日本の観光客に必要なプログラムです。
        </div>
      </div>

      {/*  */}
      <div style={{ position: "relative" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundAttachment: "fixed", backgroundImage: "url('/bg.jpeg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "50% 50%" }}>

        </div>
        <div style={{ height: "500px" }}>

        </div>
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#383838", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ float: "left", width: "45%", fontSize: "48px", textAlign: "left", paddingLeft: 150 }}>
          ストーリーツアー <br />
          だけの特徴
        </div>
        <div style={{ float: "right", width: "55%" }}>
          ストーリーツアーだけの特徴<br /><br />
          単にソウルの山を登るだけでなく、朝鮮時代の宮殿の人たちに関する文化も紹介し、<br/>
          山と伝統文化を同時に接することができます。
          <br />これにより、韓国の伝統文化に関心のある観光客にも、<br />ソウルの山に関心のある観光客にも皆楽しめることができます。<br /><br />
          登山ガイドと一緒にする山岳旅行はソウルの過去と現在の話があります。<br /><br />
          ソウルの山岳旅行は風景だけを楽しめる場所ではなく、ソウルの文化にも触れることができます。
        </div>
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#1a5339", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ margin: "0 auto", width: "1000px", display: "flex", justifyContent: "center", alignItems: "center" }}>
          <div style={{ margin: "0 10px" }}>
            <span>莉茉山</span>
            <p>
              ソウル特別市恩平区津寛洞に位置する都心の中の山だ。イマル山は朝鮮時代の都城10里の外にある山で、墓が多く、おそらく当時共同墓地だったと推定される。現在は恩平ニュータウンに属し、都心の緑地空間であり、近隣公園の役割を果たしている。
            </p>
          </div>
          <div style={{ margin: "0 10px" }}>
            <span>恩平歴史韓屋博物館</span>
            <p>
              ソウル恩平区の歴史と郷土現況などを土台に恩平区地域で発掘された遺跡を展示している。恩平区歴史館では恩平区の誕生背景と恩平ニュータウン開発の背景と恩平区から出土した遺跡と遺物などを展示している。韓屋展示館では韓国家屋の変遷史を紹介し、韓屋を作る過程と方式などを展示し、韓屋資材を通じた体験ができる。
            </p>
          </div>
          <div style={{ margin: "0 10px" }}>
            <span>韓屋村</span>
            <p>
              ソウル特別市恩平区津寛洞に位置する現代式韓屋村である。北漢山の美しい自然環境と現代式韓屋が調和した恩平区の代表的な名所だ。近くには恩平韓屋村8景があり、見どころを加え、恩平歴史韓屋博物館、ノナドゥリセンター、三人で文学館、金岩美術館など、多様な韓国文化体験施設が位置しており、展示、体験、教育など多様な文化活動が楽しめる。
            </p>
          </div>
          <div style={{ margin: "0 10px" }}>
            <span>津寬寺</span>
            <p>
              北漢山(三角山)の西麓にある高麗時代の古刹で、朝鮮時代には漢陽近郊の4大寺院の一つだった。津寛寺から北漢山の頂上方向の東に続いた渓谷を津寛寺渓谷と呼ぶが、岩盤がよく発達している。岩盤は傾斜が急で、小さな滝が渓谷に沿って続く。周辺は北漢山国立公園に指定されている。道峰山、北漢山城、僧伽寺、天竺寺などの観光地がある。
            </p>
          </div>
        </div>
      </div>

      {/*  */}
      <div style={{ position: "relative" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundAttachment: "fixed", backgroundImage: "url('/bg2.jpeg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "50% 50%" }}>

        </div>
        <div style={{ height: "500px" }}>

        </div>
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#383838", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ float: "left", width: "50%", fontSize: "48px", textAlign: "center" }}>
          申し込み
        </div>
        <div style={{ float: "right", width: "50%" }}>
          <div>
            <label>
              名前 <span style={{ color: "red" }}>*</span><br />
              <input
                style={{
                  width: "300px",
                  backgroundColor: "rgba(33, 33, 33, 0.05)",
                  border: "rgba(247, 247, 247, 0.6) solid 1px",
                  height: "34px",
                  margin: "5px 0",
                  padding: "5px 10px",
                  color: "white"
                }}
              />
            </label>
          </div>
          <div>
            <label>
              メール <span style={{ color: "red" }}>*</span><br />
              <input
                style={{
                  width: "300px",
                  backgroundColor: "rgba(33, 33, 33, 0.05)",
                  border: "rgba(247, 247, 247, 0.6) solid 1px",
                  height: "34px",
                  margin: "5px 0",
                  padding: "5px 10px",
                  color: "white"
                }}
              />
            </label>
          </div>
          <div>
            <label>
              予約日 <span style={{ color: "red" }}>*</span><br />
              <input
                style={{
                  width: "300px",
                  backgroundColor: "rgba(33, 33, 33, 0.05)",
                  border: "rgba(247, 247, 247, 0.6) solid 1px",
                  height: "34px",
                  margin: "5px 0",
                  padding: "5px 10px",
                  color: "white"
                }}
              />
            </label>
          </div>
          <div style={{ marginTop: 10 }}>
            <button style={{ width: "300px", padding: "8px", color: "white", border: "none", backgroundColor: "#f5343d" }}>
              SEND
            </button>
          </div>
        </div>
      </div>

      <footer style={{ background: "#f5343d", color: "white", padding: 50, lineHeight: .5, textAlign: "center" }}>
        <p>
          Copyright ⓒ 2022 STORY TOUR All Rights Reserved
        </p>
        <p>
          NATOUR
        </p>
      </footer>
    </div>
  )
}

export default Home
