import type { NextPage } from 'next'
import Head from 'next/head'
import Image from "next/image";
import {useEffect, useState} from "react";

const Home: NextPage = () => {

  const [fixHeader, setFixHeader] = useState(false);

  const onScroll = () => {
    const scrollTop = window.pageYOffset;
    scrollTop > 150 ? setFixHeader(true) : setFixHeader(false);
  };

  useEffect(() => {
    window.addEventListener("scroll", onScroll);
    return () => {
      window.removeEventListener("scroll", onScroll);
    };
  }, []);

  return (
    <div style={{ minWidth: "1200px" }}>
      <Head>
        <title>ストーリーツアー</title>

        <meta property="og:url" content="https://www.sanppo.co.kr/" />
        <meta property="og:title" content="ストーリーツアー" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="/main.jpeg" />
        {/*<meta property="og:description" content="공유기능 | 열심히 코드를 공부합시다." />*/}
        {/*<meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" href="/icon.svg" />
      </Head>

      <div style={{ position: "relative" }}>
        <header style={
          fixHeader ?
          { backgroundColor: "#383838", height: "150px", lineHeight: "150px", zIndex: "9999", position: "fixed", left: 0, right: 0, display: "flex", justifyContent: "space-around" } :
          { height: "150px", lineHeight: "150px", zIndex: "9999", position: "absolute", left: 0, right: 0, display: "flex", justifyContent: "space-around" }
        }>
          <div>
            <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "35px" }}>
              ストーリーツアー
            </a>
          </div>

          <div>
            <ul style={{ margin: 0, padding: 0 }}>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  会社紹介
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  プログラム
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  ギャラリー
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  CONTACT US
                </a>
              </li>
            </ul>
          </div>
          <div>
            <a href={"/Membership"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: 700, background: "#f5343d", padding: "8px 15px", borderRadius: "10px" }}>
              予約確認
            </a>
          </div>
        </header>
      </div>

      <div style={{ position: "relative", height: "900px" }}>
        <div style={{ height: "100%", backgroundImage: "url('/main.jpeg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "50% 50%" }}>

        </div>
        {/*<Image src={"/main.jpeg"} alt={"배경이미지"} fill />*/}
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#383838", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ float: "left", width: "50%", fontSize: "48px", textAlign: "center" }}>
          プログラム
        </div>
        <div style={{ float: "right", width: "50%" }}>
          屋久島で大自然を楽しむなら、ガイドさんと一緒に歩くのがオススメです。<br /><br />

          これはガイド会社だからの宣伝ではなく、多くのユーザー様から頂いた正直な意見です。<br /><br />

          ガイドさんと歩く事で屋久島の自然だけではなく、<br />歴史や文化などたくさんのストーリーを楽しく知る事が出来ます。<br />また、ケガや事故などが発生した時も適切な処置をしてくれる点も安心です。
        </div>
      </div>

      {/*  */}
      <div style={{ position: "relative" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundAttachment: "fixed", backgroundImage: "url('/bg.jpeg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "50% 50%" }}>

        </div>
        <div style={{ height: "500px" }}>

        </div>
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#383838", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ float: "left", width: "45%", fontSize: "48px", textAlign: "center" }}>
          宮之浦エリア
        </div>
        <div style={{ float: "right", width: "55%" }}>
          屋久島の玄関口「宮之浦港」からすこし歩いた小高い丘に位置するリゾートホテル。<br /><br />
          トレッキングなどで疲れた身体を癒してくれる大浴場を完備！魚介類をはじめとする新鮮な食材をふんだんに使った食事も人気です。<br /><br />
          ホテルならではの各種サービスも充実しており、快適なリゾートライフをお過ごしいただけます。<br /><br />

          屋久島の山々と名水百選の清流を望む、新鮮な海の幸を使った料理が自慢の旅館。<br /><br />
          サウナ完備の大浴場からは宮之浦川と山岳の景色を見ながら、疲れた身体を癒せます。<br /><br />
          そのほか、登山用品のレンタルコーナーやレンタサイクル、売店など館内施設も充実しています。
        </div>
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#1a5339", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ margin: "0 auto", width: "1000px", display: "flex", justifyContent: "center", alignItems: "center" }}>
          <div style={{ margin: "0 10px" }}>
            <span>莉茉山</span>
            <p>
              ソウル特別市恩平区津寛洞に位置する都心の中の山だ。イマル山は朝鮮時代の都城10里の外にある山で、墓が多く、おそらく当時共同墓地だったと推定される。現在は恩平ニュータウンに属し、都心の緑地空間であり、近隣公園の役割を果たしている。
            </p>
          </div>
          <div style={{ margin: "0 10px" }}>
            <span>恩平歴史韓屋博物館</span>
            <p>
              ソウル特別市恩平区津寛洞にある恩平区公立博物館だ。恩平韓屋村に位置し、恩平区役所が管掌する。2014年に開館した博物館で、ソウル恩平区の歴史と郷土現況などを土台に恩平区地域で発掘された遺跡を展示している。恩平区歴史館では恩平区の誕生背景と恩平ニュータウン開発の背景と恩平区から出土した遺跡と遺物などを展示している。韓屋展示館では韓国家屋の変遷史を紹介し、韓屋を作る過程と方式などを展示し、韓屋資材を通じた体験ができる。
            </p>
          </div>
          <div style={{ margin: "0 10px" }}>
            <span>韓屋村</span>
            <p>
              ソウル特別市恩平区津寛洞に位置する現代式韓屋村である。韓屋村の近くには北漢山と津寬寺がある。北漢山の美しい自然環境と現代式韓屋が調和した恩平区の代表的な名所だ。近くには恩平韓屋村8景があり、見どころを加え、恩平歴史韓屋博物館、ノナドゥリセンター、三人で文学館、金岩美術館など、多様な韓国文化体験施設が位置しており、展示、体験、教育など多様な文化活動が楽しめる。
            </p>
          </div>
          <div style={{ margin: "0 10px" }}>
            <span>津寬寺</span>
            <p>
              北漢山(三角山)の西麓にある高麗時代の古刹で、朝鮮時代には漢陽近郊の4大寺院の一つだった。津寛寺から北漢山の頂上方向の東に続いた渓谷を津寛寺渓谷と呼ぶが、岩盤がよく発達している。岩盤は傾斜が急で、小さな滝が渓谷に沿って続く。周辺は北漢山国立公園に指定されている。道峰山、北漢山城、僧伽寺、天竺寺などの観光地がある。
            </p>
          </div>
        </div>
      </div>

      {/*  */}
      <div style={{ position: "relative" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundAttachment: "fixed", backgroundImage: "url('/bg2.jpeg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "50% 50%" }}>

        </div>
        <div style={{ height: "500px" }}>

        </div>
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#383838", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ float: "left", width: "50%", fontSize: "48px", textAlign: "center" }}>
          申し込み
        </div>
        <div style={{ float: "right", width: "50%" }}>
          <div>
            <label>
              名前 <span style={{ color: "red" }}>*</span><br />
              <input
                style={{
                  width: "300px",
                  backgroundColor: "rgba(33, 33, 33, 0.05)",
                  border: "rgba(247, 247, 247, 0.6) solid 1px",
                  height: "34px",
                  margin: "5px 0",
                  padding: "5px 10px",
                  color: "white"
                }}
              />
            </label>
          </div>
          <div>
            <label>
              メール <span style={{ color: "red" }}>*</span><br />
              <input
                style={{
                  width: "300px",
                  backgroundColor: "rgba(33, 33, 33, 0.05)",
                  border: "rgba(247, 247, 247, 0.6) solid 1px",
                  height: "34px",
                  margin: "5px 0",
                  padding: "5px 10px",
                  color: "white"
                }}
              />
            </label>
          </div>
          <div>
            <label>
              予約日 <span style={{ color: "red" }}>*</span><br />
              <input
                style={{
                  width: "300px",
                  backgroundColor: "rgba(33, 33, 33, 0.05)",
                  border: "rgba(247, 247, 247, 0.6) solid 1px",
                  height: "34px",
                  margin: "5px 0",
                  padding: "5px 10px",
                  color: "white"
                }}
              />
            </label>
          </div>
          <div style={{ marginTop: 10 }}>
            <button style={{ width: "300px", padding: "8px", color: "white", border: "none", backgroundColor: "#f5343d" }}>
              SEND
            </button>
          </div>
        </div>
      </div>

      <footer style={{ background: "#f5343d", color: "white", padding: 50, lineHeight: .5, textAlign: "center" }}>
        <p>
          Copyright ⓒ 2022 STORY TOUR All Rights Reserved
        </p>
        <p>
          NATOUR
        </p>
      </footer>
    </div>
  )
}

export default Home
