import type { NextPage } from 'next'
import Head from 'next/head'
import Image from "next/image";
import {useEffect, useState} from "react";

const Home: NextPage = () => {

  const [fixHeader, setFixHeader] = useState(false);

  const onScroll = () => {
    const scrollTop = window.pageYOffset;
    scrollTop > 150 ? setFixHeader(true) : setFixHeader(false);
  };

  useEffect(() => {
    window.addEventListener("scroll", onScroll);
    return () => {
      window.removeEventListener("scroll", onScroll);
    };
  }, []);

  return (
    <div style={{ minWidth: "1200px" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ position: "relative" }}>
        <header style={
          fixHeader ?
          { backgroundColor: "#383838", height: "150px", lineHeight: "150px", zIndex: "9999", position: "fixed", left: 0, right: 0, display: "flex", justifyContent: "space-around" } :
          { height: "150px", lineHeight: "150px", zIndex: "9999", position: "absolute", left: 0, right: 0, display: "flex", justifyContent: "space-around" }
        }>
          <div>
            <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "35px" }}>
              ストーリーツアー
            </a>
          </div>

          <div>
            <ul style={{ margin: 0, padding: 0 }}>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  会社紹介
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  プログラム
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  ギャラリー
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  CONTACT US
                </a>
              </li>
            </ul>
          </div>
          <div>
            <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: 700, background: "#f5343d", padding: "8px 15px", borderRadius: "10px" }}>
              予約確認
            </a>
          </div>
        </header>
      </div>

      <div style={{ position: "relative", height: "900px" }}>
        <div style={{ height: "100%", backgroundImage: "url('/main.jpeg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "50% 50%" }}>

        </div>
        {/*<Image src={"/main.jpeg"} alt={"배경이미지"} fill />*/}
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#383838", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ float: "left", width: "50%", fontSize: "48px", textAlign: "center" }}>
          プログラム
        </div>
        <div style={{ float: "right", width: "50%" }}>
          屋久島で大自然を楽しむなら、ガイドさんと一緒に歩くのがオススメです。<br /><br />

          これはガイド会社だからの宣伝ではなく、多くのユーザー様から頂いた正直な意見です。<br /><br />

          ガイドさんと歩く事で屋久島の自然だけではなく、<br />歴史や文化などたくさんのストーリーを楽しく知る事が出来ます。<br />また、ケガや事故などが発生した時も適切な処置をしてくれる点も安心です。
        </div>
      </div>

      {/*  */}
      <div style={{ position: "relative" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundAttachment: "fixed", backgroundImage: "url('/bg.jpeg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "50% 50%" }}>

        </div>
        <div style={{ height: "500px" }}>

        </div>
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#383838", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ float: "left", width: "45%", fontSize: "48px", textAlign: "center" }}>
          宮之浦エリア
        </div>
        <div style={{ float: "right", width: "55%" }}>
          屋久島の玄関口「宮之浦港」からすこし歩いた小高い丘に位置するリゾートホテル。<br /><br />
          トレッキングなどで疲れた身体を癒してくれる大浴場を完備！魚介類をはじめとする新鮮な食材をふんだんに使った食事も人気です。<br /><br />
          ホテルならではの各種サービスも充実しており、快適なリゾートライフをお過ごしいただけます。<br /><br />

          屋久島の山々と名水百選の清流を望む、新鮮な海の幸を使った料理が自慢の旅館。<br /><br />
          サウナ完備の大浴場からは宮之浦川と山岳の景色を見ながら、疲れた身体を癒せます。<br /><br />
          そのほか、登山用品のレンタルコーナーやレンタサイクル、売店など館内施設も充実しています。
        </div>
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#1a5339", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ margin: "0 auto", width: "1000px", display: "flex", justifyContent: "center", alignItems: "center" }}>
          <div style={{ margin: "0 10px" }}>
            <span>이말산</span>
            <p>
              Lorem Ipsum, you need to besure there  anything embarrassing hidden in the middle of text.
            </p>
          </div>
          <div style={{ margin: "0 10px" }}>
            <span>한옥박물관</span>
            <p>
              Lorem Ipsum, you need to besure there ist anything embarrassing hidden in the middle of text.
            </p>
          </div>
          <div style={{ margin: "0 10px" }}>
            <span>한옥마을</span>
            <p>
              Lorem Ipsum, you need to besure there isn anything embarrassing hidden in the middle of text.
            </p>
          </div>
          <div style={{ margin: "0 10px" }}>
            <span>진관사</span>
            <p>
              Lorem Ipsum, you need to besure there anything embarrassing hidden in the middle of text.
            </p>
          </div>
        </div>
      </div>

      {/*  */}
      <div style={{ position: "relative" }}>
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundAttachment: "fixed", backgroundImage: "url('/bg2.jpeg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "50% 50%" }}>

        </div>
        <div style={{ height: "500px" }}>

        </div>
      </div>

      {/* 배너 */}
      <div style={{ backgroundColor: "#383838", color: "white", overflow: "hidden", padding: "110px" }}>
        <div style={{ float: "left", width: "50%", fontSize: "48px", textAlign: "center" }}>
          申し込み
        </div>
        <div style={{ float: "right", width: "50%" }}>
          <div>
            <label>
              名前 <span style={{ color: "red" }}>*</span><br />
              <input
                style={{
                  width: "300px",
                  backgroundColor: "rgba(33, 33, 33, 0.05)",
                  border: "rgba(247, 247, 247, 0.6) solid 1px",
                  height: "34px",
                  margin: "5px 0",
                  padding: "5px 10px",
                  color: "white"
                }}
              />
            </label>
          </div>
          <div>
            <label>
              メール <span style={{ color: "red" }}>*</span><br />
              <input
                style={{
                  width: "300px",
                  backgroundColor: "rgba(33, 33, 33, 0.05)",
                  border: "rgba(247, 247, 247, 0.6) solid 1px",
                  height: "34px",
                  margin: "5px 0",
                  padding: "5px 10px",
                  color: "white"
                }}
              />
            </label>
          </div>
          <div>
            <label>
              予約日 <span style={{ color: "red" }}>*</span><br />
              <input
                style={{
                  width: "300px",
                  backgroundColor: "rgba(33, 33, 33, 0.05)",
                  border: "rgba(247, 247, 247, 0.6) solid 1px",
                  height: "34px",
                  margin: "5px 0",
                  padding: "5px 10px",
                  color: "white"
                }}
              />
            </label>
          </div>
          <div style={{ marginTop: 10 }}>
            <button style={{ width: "300px", padding: "8px", color: "white", border: "none", backgroundColor: "#f5343d" }}>
              SEND
            </button>
          </div>
        </div>
      </div>

      <footer style={{ background: "#f5343d", color: "white", padding: 50, lineHeight: .5, textAlign: "center" }}>
        <p>
          Copyright ⓒ 2022 STORY TOUR All Rights Reserved
        </p>
        <p>
          NATOUR
        </p>
      </footer>
    </div>
  )
}

export default Home
