import type { NextPage } from 'next'
import Head from "next/head";
import {useEffect, useState} from "react";

const Membership: NextPage = () => {

  const [fixHeader, setFixHeader] = useState(false);

  const onScroll = () => {
    const scrollTop = window.pageYOffset;
    scrollTop > 150 ? setFixHeader(true) : setFixHeader(false);
  };

  useEffect(() => {
    window.addEventListener("scroll", onScroll);
    return () => {
      window.removeEventListener("scroll", onScroll);
    };
  }, []);

  return (
    <div style={{ minWidth: "1200px" }}>
      <Head>
        <title>ストーリーツアー - 会員加入</title>

        <meta property="og:url" content="https://www.sanppo.co.kr/" />
        <meta property="og:title" content="ストーリーツアー" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="/main.jpeg" />
        {/*<meta property="og:description" content="공유기능 | 열심히 코드를 공부합시다." />*/}
        {/*<meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" href="/icon.svg" />
      </Head>

      <div style={{ position: "relative" }}>
        <header style={
          fixHeader ?
            { backgroundColor: "#383838", height: "150px", lineHeight: "150px", zIndex: "9999", position: "fixed", left: 0, right: 0, display: "flex", justifyContent: "space-around" } :
            { backgroundColor: "rgba(0, 0, 0, .2)", height: "150px", lineHeight: "150px", zIndex: "9999", position: "absolute", left: 0, right: 0, display: "flex", justifyContent: "space-around" }
        }>
          <div>
            <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "35px" }}>
              ストーリーツアー
            </a>
          </div>

          <div>
            <ul style={{ margin: 0, padding: 0 }}>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  会社紹介
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/Products/Imalsan"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  プログラム
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  ギャラリー
                </a>
              </li>
              <li style={{ display: "inline-block", padding: "0 20px" }}>
                <a href={"/"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: "700" }}>
                  CONTACT US
                </a>
              </li>
            </ul>
          </div>
          <div>
            <a href={"/Membership"} target={"_parent"} style={{ color: "white", fontSize: "15px", fontWeight: 700, background: "#f5343d", padding: "8px 15px", borderRadius: "10px" }}>
              予約確認
            </a>
          </div>
        </header>
      </div>

      <div style={{ position: "relative", height: "900px" }}>
        <div style={{ height: "100%", backgroundImage: "url('/membership_bg.jpg')", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "50% 50%" }}>
          <div
            style={{
              position: "absolute",
              left: "50%",
              top: "50%",
              width: 500,
              height: 520,
              backgroundColor: "rgba(0,0,0,.5)",
              transform: "translate(-100%, -40%)",
              color: "white",
              padding: "30px 50px",
            }}
          >
            <h5 style={{ fontSize: 24 }}>会員加入</h5>
            <div style={{ marginBottom: 20 }}>
              <label style={{ display: "block", fontSize: 18, margin: "5px 0" }}> ユーザID </label>
              <input style={{ width: "100%", lineHeight: "34px", padding: "0 10px", fontSize: 16 }} type={"text"} placeholder={"IDの入力"} />
            </div>
            <div style={{ marginBottom: 20 }}>
              <label style={{ display: "block", fontSize: 18, margin: "5px 0" }}> パスワード </label>
              <input style={{ width: "100%", lineHeight: "34px", padding: "0 10px", fontSize: 16 }} type={"password"} placeholder={"パスワードの入力"} />
            </div>
            <div style={{ marginBottom: 50 }}>
              <label style={{ display: "block", fontSize: 18, margin: "5px 0" }}> パスワードを確認。 </label>
              <input style={{ width: "100%", lineHeight: "34px", padding: "0 10px", fontSize: 16 }} type={"password"} placeholder={"パスワードの入力"} />
            </div>
            <div>
              <a href={"/Membership"} style={{ display: "block", width: "100%", height: 47, padding: 10, fontSize: 16, color: "white", backgroundColor: "#f5343e", borderRadius: 10, textAlign: "center" }}>
                Sign in
              </a>
            </div>

          </div>
        </div>
        {/*<Image src={"/main.jpeg"} alt={"배경이미지"} fill />*/}
      </div>
    </div>
  )
}

export default Membership
